### ISSUE TITLE
muk_account_bank_statement_import_sheet- Import of bank statement error

### ISSUE THREAD

**Issue by vinodkumarkolli** [muk-it/muk_misc#12]
Importing the 'sample Template statement (xls)' provided by MuKIT itself is failing to import with following error 
>>>>>
Import preview failed due to: Unsupported file format "text/csv", import only supports CSV, ODS, XLS and XLSX.
For CSV files, you may need to select the correct separator.
Here is the start of the file we could not import:
<<<<<<<

Where should i modify the file format?

Thanks in Advance

**Comment by keshrath** [comment]
Can't reproduce that error.

![ezgif com-video-to-gif (26)](https://user-images.githubusercontent.com/4851083/61821401-69af6180-ae57-11e9-83c2-4139b3cfc844.gif)
