### ISSUE TITLE
MUK mail branding should depends on mail_bot

### ISSUE THREAD

**Issue by Yakulu** [muk-it/muk_misc#2]
Good evening,

As `muk_mail_branding` uses data (for example [this field](https://github.com/muk-it/muk_misc/blob/12.0/muk_mail_branding/models/res_users.py#L26)) from official `mail_bot` addon, it should depends on it. Otherwise, if you have `muk_mail_branding` installed and you uninstall `mail_bot`, you will get error 500.

Thanks for your work.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_misc/commit/90d5b667babc50ae64fbd1e4ffff119edc8bfd08
