### ISSUE TITLE
Muk saas branding > not show favicon and logo on login page

### ISSUE THREAD

**Issue by nvietthuan2010** [muk-it/muk_misc#5]
when login that issues is XML Parsing Error: no root element found /webclient/qweb?mods= Line Number 1, Column 1

**Comment by keshrath** [comment]
I need more information: How do I reproduce the error or where does the error occur?

**Comment by nvietthuan2010** [comment]
i am using odoo version 12. error is show on login page, when i logined is not error. may be controller is issues bug.

**Comment by nvietthuan2010** [comment]
![image](https://user-images.githubusercontent.com/45958028/55342159-52c4b800-54d2-11e9-8896-4edd59709f5a.png)

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_misc/issues/7
