### ISSUE TITLE
muk_account_bank_statement_import_sheet - Improvement suggestion

### ISSUE THREAD

**Issue by gbeuning** [muk-it/muk_misc#6]
Suggestion to add the following account_bank_statement_line related fields to class AccountBankStatementImportWizard() in account_bank_statement_import_wizard.py:

**account_number**    
If the bank statement provides the Account Number of the partner, and partners have been configured properly, importing the account number will improve the automatic reconciliation process (to find a matching partner that is also based on the partner's account number in stead of only based on the partner's name). Note that the account number to be imported has to be formatted as 'pretty IBAN' (IBAN represented in groups of four characters separated by a single space) else Odoo source will not find a match. For reference on the matching process in Odoo see SQL code in method _get_bank_statement_line_partners() of class AccountReconciliation(). Here it is clear that the check is on the res_partner_bank.acc_number. For IBAN this is the number containing spaces for improved readability. If the bank statement import line contains the bank account numbers without spaces, the check should actually be done on res_partner_bank.sanitized_acc_number. Also note that there is currently no check on the res_partner_bank.acc_holder_name.
      
**unique_import_id**
If the bank statement provides a UID, importing it as the unique_import_id prevents that the same bank statement line is imported twice. 
      
Above was tested in Odoo v12 CE (12.0-20190117).

**Comment by keshrath** [comment]
That's a very good point. This should add the additional fields: https://github.com/muk-it/muk_misc/commit/83c33809cdba659dac9afe01fe15e618ccd59640

**Comment by gbeuning** [comment]
Thanks for the additions, it works well!
