### ISSUE TITLE
12.0 > Favicon & Logo & Company name

### ISSUE THREAD

**Issue by gregory-moka** [muk-it/muk_misc#7]
Hello,
Since the last Web Branding app's update, there is no way to set the company favicon, logo & company name. Even if they are defined in Settings > Branding configuration page, the Mukit Logo and favicon are always displayed on the login page and probably on all other pages.

![image](https://user-images.githubusercontent.com/45974412/55940444-727d7e00-5c40-11e9-82b4-112cec56a826.png)

![image](https://user-images.githubusercontent.com/45974412/55940366-4235df80-5c40-11e9-8ff9-4d4d32d82395.png)

Is there something I should do ? Another app is not up to date ?
Thanks for all

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_misc/tree/12.0/muk_saas_branding/static/src/img

**Comment by keshrath** [comment]
Replace the files here

**Comment by keshrath** [comment]
To customize the login page

**Comment by keshrath** [comment]
Since this module need to be activated even if no database is selected it should be loaded right at the server start. This can be done by editing the configuration file or passing a load parameter to the start script.

Parameter: --load=web,muk_saas_branding

The following fields can be modified in the config file:

database_manager_system_name
database_manager_system_logo_url
database_manager_system_favicon_url
database_manager_privacy_policy_url

**Comment by gregory-moka** [comment]
This "issue" happens only on database without website's app installed.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_misc/commit/b467d7a86940ae69e4f946bcf4bcb5b920cf8f9e

**Comment by nvietthuan2010** [comment]
> 
> 
> Since this module need to be activated even if no database is selected it should be loaded right at the server start. This can be done by editing the configuration file or passing a load parameter to the start script.
> 
> Parameter: --load=web,muk_saas_branding
> 
> The following fields can be modified in the config file:
> 
> database_manager_system_name
> database_manager_system_logo_url
> database_manager_system_favicon_url
> database_manager_privacy_policy_url

if i config in odoo.conf then --load what's mean?

**Comment by keshrath** [comment]
odoo.conf -> server_wide_modules = web,muk_saas_branding

**Comment by gregory-moka** [comment]
Tanks a lot :)
